import type { Metadata } from "next";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import Button, { Arrow } from "../components/Button";
import CodeBlock from "../components/CodeBlock";
import SalesforceScreenshot from "../components/SalesforceScreenshot";
import s from "../product-pages.module.css";

export const metadata: Metadata = { title: "Salesforce Calendar Integration", description: "Embed forceCalendar in Salesforce Lightning. Released package, standard Events, Apex permissions, Lightning Web Security, and a deliberate installation guide.", alternates: {canonical:"https://forcecalendar.org/salesforce"}, openGraph: {url:"https://forcecalendar.org/salesforce"} };
const sandbox = "https://test.salesforce.com/packaging/installPackage.apexp?p0=04tg5000000ExTFAA0";
const production = "https://login.salesforce.com/packaging/installPackage.apexp?p0=04tg5000000ExTFAA0";
const releases = "https://github.com/forceCalendar/salesforce/releases";
const permissions = "https://github.com/forceCalendar/salesforce/blob/master/docs/PERMISSIONS.md";

export default function SalesforcePage() {
  return <div className={s.page}><Nav /><main>
    <header className={s.hero}><div className={s.wrap}><p className={s.eyebrow}>Salesforce / Lightning + Apex / released 0.3.0.1</p><div className={s.heroGrid}><h1 className={`${s.title} ${s.blue}`}>Your Events.<br /><span>In their element.</span></h1><div><p className={s.lede}>Put a real calendar on your Lightning pages, beside the customer and record context your team already uses. Standard Salesforce Events, an adaptable interface, and access enforced in Apex.</p><div className={s.actions}><Button href={sandbox}>Install in a sandbox <Arrow /></Button><Button href="#install" variant="secondary">Installation guide</Button></div></div></div><div className={s.specimen}><div className={s.specimenTop}><span>Actual Lightning capture / synthetic sample data</span><span>Month · week · day</span></div><SalesforceScreenshot src="/salesforce-lightning-week-clean.png" alt="Genuine Salesforce Lightning calendar showing synthetic appointments in a week view" caption="Week view" sizes="(max-width: 1200px) 100vw, 1180px" /></div><div className={s.rail}><span>Released installer 0.3.0.1</span><span>Package: Core 2.5.6 / Interface 1.9.0</span><span>Website demo: Core 2.5.7 / Interface 1.9.1</span></div></div></header>

    <section className={s.section}><div className={s.wrap}><div className={s.factStrip}><div><h3>A calendar over standard Events</h3><p>Create, read, edit, delete, and navigate accessible Salesforce Event records. Record-page context follows supported Event relationships.</p></div><div><h3>Bundled inside your org</h3><p>The LWC loads Core and Interface from a static resource. Calendar assets do not need a runtime CDN.</p></div><div><h3>Validate the access model</h3><p>Sharing and user-mode access apply in Apex. Configure permissions intentionally and test representative users before rollout.</p></div></div></div></section>

    <section className={`${s.section} ${s.dark}`} id="architecture"><div className={s.wrap}><p className={s.eyebrow}>The integration, end to end</p><h2 className={s.heading}>A familiar record.<br />A richer way to work with it.</h2><p className={s.lede}>The calendar is the interface. Salesforce remains the record system.</p><div className={s.flow}>{[{n:"01",title:"Salesforce Event",text:"Your records, relationships, sharing, and org rules."},{n:"02",title:"Apex controller",text:"Queries and writes with sharing and user-mode CRUD/FLS enforcement."},{n:"03",title:"Lightning component",text:"Loads the bundle, requests the visible range, and forwards changes."},{n:"04",title:"Calendar UI",text:"Month, week, day, and event forms. The response returns through the same data boundary."}].map(item=><div key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></div>)}</div><p className={`${s.note} mt-6`}>Lightning Web Security is required. Legacy Lightning Locker is not supported for the third-party custom elements used here. <a className={s.link} href="https://developer.salesforce.com/docs/platform/lwc/guide/create-use-custom-elements.html">Official Salesforce guidance <Arrow /></a></p></div></section>

    <section className={s.section} id="install"><div className={`${s.wrap} ${s.split}`}><div><p className={s.eyebrow}>From package to Lightning page</p><h2 className={s.heading}>Start in a sandbox.<br />Roll out deliberately.</h2><p className={s.note}>Released unlocked package 0.3.0.1 passed a clean install and 32 Apex test methods, with 98% package coverage. These checks do not replace validation in your own org.</p><div className={s.actions}><a href={releases} className={s.link}>Review releases <Arrow /></a></div></div><div className={s.steps}>
      <article className={s.step}><span className={s.stepNumber}>01</span><div><h3>Check the prerequisites</h3><p>Use Lightning Experience with Lightning Web Security enabled. An admin or developer needs package installation rights and access to Lightning App Builder. Confirm that standard Event records fit your use case.</p></div></article>
      <article className={s.step}><span className={s.stepNumber}>02</span><div><h3>Install the released package</h3><p>Choose Install for Admins Only, then grant access to the intended users. Keep a record of the exact version you test.</p><div className={s.actions}><Button href={sandbox}>Install in a sandbox</Button><Button href={production} variant="secondary">Production / Developer Edition</Button></div><p className={`${s.note} mt-4`}>Production installation is available. Complete your sandbox checks first. Package 0.3.0.1 freezes Core 2.5.6 and Interface 1.9.0; npm updates do not change that package.</p></div></article>
      <article className={s.step}><span className={s.stepNumber}>03</span><div><h3>Add the component and assign access</h3><ol><li>Open Setup → Lightning App Builder and edit an App, Home, or Record page.</li><li>Add ForceCalendar Demo to check sample-data rendering. It has no Apex data access.</li><li>Add Force Calendar for actual Event records, then save and activate the page for your intended users.</li><li>Assign the minimum permission set needed and verify access to the related records.</li></ol></div></article>
      <article className={s.step}><span className={s.stepNumber}>04</span><div><h3>Validate the whole interaction</h3><p>Use disposable synthetic records with a representative non-admin user. Test create, edit, cancel, confirmed delete, reload, navigation, all-day dates, Record page relationships, read-only behavior, and denied access. Check your org’s validation rules and flows, then run the Apex tests.</p><p className="mt-3">Deploy the same version you validated, repeat page activation and permission assignments, and verify the production experience as an intended user.</p></div></article>
    </div></div></section>

    <section className={`${s.section} border-y border-hairline bg-sunken`} id="permissions"><div className={`${s.wrap} ${s.split}`}><div><p className={s.eyebrow}>Access is part of the integration</p><h2 className={s.heading}>Give each user<br />the right surface area.</h2><p className={s.note}>No permission set is assigned automatically. Read-only UI is a convenience; Apex and Salesforce permissions enforce data access.</p><a className={`${s.link} mt-5`} href={permissions}>Full permissions reference <Arrow /></a></div><div><div className={s.permission}><div><h3>ForceCalendarAccess</h3><p>Controller access only. Use it when your org manages activity and field permissions separately.</p></div><div><h3>ForceCalendarReader</h3><p>Controller access, Access Activities, and read access to the five configurable fields used by the component.</p></div><div><h3>ForceCalendarEditor</h3><p>Reader access plus Edit Events and field edit access. Edit Events permits create, update, and delete subject to sharing.</p></div></div><p className={`${s.note} mt-5`}>Permission sets are additive: Reader does not revoke permissions elsewhere. These sets do not grant related Account, Contact, or Lead access, Edit Tasks, View All, or Modify All. Access Activities applies beyond this calendar. Salesforce shares Description, WhoId, and WhatId permissions with Task; Subject, StartDateTime, and EndDateTime do not have independent configurable field permissions.</p></div></div></section>

    <section className={s.section} id="configuration"><div className={s.wrap}><div className={s.split}><div><p className={s.eyebrow}>Configuration & boundaries</p><h2 className={s.heading}>Know what your<br />page will do.</h2></div><div><div className={s.settings}><div><h3>currentView</h3><p>month / week / day. The initial view defaults to month.</p></div><div><h3>height</h3><p>800px by default. Choose an appropriate CSS height and test smaller screens.</p></div><div><h3>readOnly</h3><p>Disables editing and dragging while preserving navigation and selection. Save callbacks are also blocked.</p></div></div>
      <details className={s.disclosure}><summary>App, Home, and Record pages</summary><p>App and Home pages show accessible Events in the requested date range; this guide configures no owner-only filter. Record pages filter through WhoId or WhatId. Contact and Lead contexts use WhoId; supported related records use WhatId. Access to that object and record is still required. Related child records are not automatically included.</p></details>
      <details className={s.disclosure}><summary>Recurrence, dates, and query limits</summary><p>Native recurring Salesforce Events remain read-only here; manage series and occurrences in Salesforce Calendar. All-day events use inclusive civil dates. The query returns at most 1,000 records per requested date range. Tasks, custom-object calendars, and resource booking are not configured by this integration guide.</p></details>
      <details className={s.disclosure}><summary>What was actually verified?</summary><p>The production LWC was tested against actual Salesforce Events using disposable synthetic fixtures, including editing, confirmed deletion, refresh, navigation, and inclusive all-day dates. Restricted-user behavior has isolated Apex tests; an actual restricted-user Lightning session has not been tested. The screenshots below show an earlier synthetic demo capture, not the installation or permission tests.</p></details>
    </div></div></div></section>

    <section className={`${s.section} ${s.dark}`} id="developers"><div className={`${s.wrap} ${s.split}`}><div><p className={s.eyebrow}>Alternative / deploy from source</p><h2 className={s.heading}>Keep the full stack<br />on one revision.</h2><p className={s.lede}>Deploy the LWC, Apex controller, and static resource together. Build dependencies live in both the repository root and src directory.</p><p className={`${s.note} mt-5`}>Use an authenticated sandbox alias. A source checkout and its resolved dependencies can differ from the released package.</p></div><CodeBlock filename="Terminal" code={`git clone https://github.com/forcecalendar/salesforce.git
cd salesforce
npm ci
cd src
npm ci
cd ..
npm run build
cd dist
sf project deploy start --source-dir force-app --target-org your-sandbox-alias
sf apex run test --class-names ForceCalendarControllerTest --target-org your-sandbox-alias --result-format human --wait 10`} /></div></section>

    <section className={s.section} id="screenshots"><div className={s.wrap}><p className={s.eyebrow}>Genuine Lightning specimens</p><h2 className={s.heading}>A view for the way you work.</h2><p className={`${s.note} mb-7`}>Core 2.5.5 · Interface 1.8.1 · October 2026 captures. Real Lightning pixels with synthetic sample data; they do not verify the current package or your org’s data access.</p><div className={s.gallery}><SalesforceScreenshot src="/salesforce-lightning-month-clean.png" alt="Genuine Lightning month view with synthetic calendar events" caption="Month view" /><SalesforceScreenshot src="/salesforce-lightning-day-clean.png" alt="Genuine Lightning day view with synthetic appointments" caption="Day view" /><SalesforceScreenshot src="/salesforce-lightning-editor-clean.png" alt="Genuine Lightning event creation form with synthetic sample data" caption="Event creation · synthetic sample-data workflow" height={663} /></div></div></section>
    <div className={s.wrap}><div className={s.end}><div><p className={s.eyebrow}>Explore before you integrate</p><h2 className="mt-3">Try the calendar in the playground.</h2></div><Button href="/playground">Open playground <Arrow /></Button></div></div>
  </main><Footer /></div>;
}
