import type { Metadata } from "next";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import Button, { Arrow } from "../components/Button";
import CodeBlock from "../components/CodeBlock";
import s from "../product-pages.module.css";

export const metadata: Metadata = { title:"Platforms & Integration Paths", description:"Choose the right forceCalendar integration: a released Salesforce distribution, browser components, a headless engine, or platform-specific developer starters.",alternates:{canonical:"https://forcecalendar.org/platforms"},openGraph:{url:"https://forcecalendar.org/platforms"} };
const examples = "https://github.com/forceCalendar/examples";
const starters = [
 {name:"Browser applications",status:"Runnable starter",detail:"A vanilla Vite example for embedding the Web Component in your application. Start with local events, then connect your authorized data layer.",slug:"vanilla-vite",check:"Verify record mapping, event callbacks, persistence, and keyboard interaction in your app."},
 {name:"Cloudflare Workers",status:"Headless starter",detail:"An example using Core for recurrence expansion, conflict detection, and ICS export in an edge handler.",slug:"cloudflare-worker-scheduling",check:"Review the handler, runtime limits, request authorization, and workload size before deployment."},
 {name:"Chrome Extensions",status:"Manifest V3 starter",detail:"A packaged calendar interface for an extension popup, with vendored assets and an example manifest.",slug:"chrome-extension-mv3",check:"Review requested extension permissions and validate the manifest and content-security policy."},
 {name:"SharePoint & Teams",status:"SPFx starter",detail:"A calendar web-part starting point for Microsoft 365 pages and Teams tabs. Adapt its data and deployment model to your tenant.",slug:"sharepoint-spfx-webpart",check:"Validate the SPFx toolchain, tenant deployment, identity, and data permissions."},
 {name:"ServiceNow",status:"Service Portal starter",detail:"A widget example over ServiceNow table data. Your instance determines records, access rules, and supported portal behavior.",slug:"servicenow-portal-widget",check:"Review ACLs, table queries, field mappings, and the target instance’s widget policies."},
 {name:"Atlassian Forge",status:"Custom UI starter",detail:"A sprint-calendar example presented through Forge Custom UI. Use it as an implementation reference for your own application.",slug:"atlassian-forge-app",check:"Verify scopes, host integration, static assets, and deployment against current Forge requirements."},
];
export default function PlatformsPage(){return <div className={s.page}><Nav/><main>
 <header className={s.hero}><div className={s.wrap}><p className={s.eyebrow}>Platforms / choose the right integration surface</p><div className={s.heroGrid}><h1 className={s.title}>Your stack.<br/><span>Its calendar.</span></h1><div><p className={s.lede}>Bring calendar capabilities into the application you already own. Use the released Salesforce distribution, embed the UI in a web app, or call the engine without a browser.</p><div className={s.actions}><Button href="/salesforce">Start with Salesforce <Arrow/></Button><Button href="/playground" variant="secondary">Try the playground</Button></div></div></div><div className={`${s.boundary} !mt-10`}><div><p className={s.eyebrow}>Ready distribution</p><h3 className="mt-4">Salesforce Lightning</h3><p>Released unlocked package, LWC, Apex over standard Event records, and an installation and permissions guide.</p></div><div><p className={s.eyebrow}>Developer building blocks</p><h3 className="mt-4">Your application + an adapter</h3><p>Core and Interface packages plus example projects. Other platform starters are not equivalent packaged integrations.</p></div></div></div></header>
 <section className={`${s.section} ${s.dark}`}><div className={s.wrap}><p className={s.eyebrow}>One library / different host boundaries</p><h2 className={s.heading}>Put each responsibility<br/>where it belongs.</h2><div className={s.flow}>{[{n:"01",title:"Your records",text:"Fetch and authorize events using your platform’s identity and data layer."},{n:"02",title:"Your adapter",text:"Map IDs, dates, fields, and mutation callbacks. Persist changes deliberately."},{n:"03",title:"Calendar engine",text:"Use Core for reusable event, recurrence, query, and conflict logic."},{n:"04",title:"Your surface",text:"Render the calendar component or expose headless operations to application code."}].map(item=><div key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></div>)}</div><p className={`${s.note} mt-6`}>Host compatibility requires host-specific validation. No library replaces your platform’s identity, permissions, content-security policy, or deployment checks.</p></div></section>
 <section className={s.section} id="starters"><div className={s.wrap}><div className={s.split}><div><p className={s.eyebrow}>Developer examples</p><h2 className={s.heading}>Start closer<br/>to your environment.</h2></div><p className={s.lede}>These repository examples show integration patterns. They are intentionally minimal starters, not supported products or a claim of verified production compatibility in your account.</p></div><div className={`${s.integration} mt-10`}>{starters.map(item=><article className={s.integrationRow} key={item.slug}><div><h3>{item.name}</h3><span className={s.status}>{item.status}</span></div><div><p>{item.detail}</p><details className={s.disclosure}><summary>Before you deploy</summary><p>{item.check}</p></details></div><a className={s.link} href={`${examples}/tree/main/${item.slug}`}>View starter <Arrow/></a></article>)}</div></div></section>
 <section className={`${s.section} border-y border-hairline bg-sunken`}><div className={`${s.wrap} ${s.split}`}><div><p className={s.eyebrow}>The mapping is yours</p><h2 className={s.heading}>Your record model.<br/>A common event shape.</h2><p className={s.lede}>Transform authorized source records into calendar events. A snapshot updates the view; it is not a request to write those records back to the source system.</p><a className={`${s.link} mt-5`} href="https://docs.forcecalendar.org">Read integration documentation <Arrow/></a></div><CodeBlock filename="application-adapter.js" code={`// Illustrative mapping: adapt these fields to your schema.
const events = authorizedRecords.map(record => ({
  id: String(record.id),
  title: record.subject,
  start: record.startsAt,
  end: record.endsAt,
}));

calendar.setEvents(events);

// Separately authorize and persist user changes.
// Use your platform's own API and access controls.`}/></div></section>
 <section className={s.section}><div className={`${s.wrap} ${s.split}`}><div><p className={s.eyebrow}>Interoperability, precisely</p><h2 className={s.heading}>Files, tools,<br/>and future connections.</h2></div><div><details open className={s.disclosure}><summary>iCalendar / ICS</summary><p>Core supports file import and export. An ICS file is not a connected Apple, Google, or Microsoft account. Live account synchronization is not shipped.</p></details><details className={s.disclosure}><summary>Headless & agent callers</summary><p>An agent can use the same headless engine through an application-owned adapter. Authorization, storage, and execution remain your application’s responsibility. The separate scoped-tool adapter is a private prototype, not a public hosted service.</p></details><details className={s.disclosure}><summary>Salesforce security compatibility</summary><p>Lightning Web Security is required for the third-party custom elements used by the Salesforce integration. Legacy Lightning Locker is not supported. Use the dedicated Salesforce guide for Apex permissions, package contents, and validation scope.</p></details></div></div></section>
 <div className={s.wrap}><div className={s.end}><div><p className={s.eyebrow}>Try the behavior before the integration</p><h2 className="mt-3">Explore a working calendar.</h2></div><Button href="/playground">Open playground <Arrow/></Button></div></div>
 </main><Footer/></div>;}
